language: node_js
node_js:
- node
script:
- yarn build
- yarn lint
- yarn coverage
deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  skip_cleanup: true
  api_key:
    secure: AdPUhRyr1L+VEt4oF99lQc8pSxcWVMxC0/g29VV6lu7MvI6iWBV/x7vqWETKF+C6ESYGj8aDopsBHeHoxALn8zuliuOc69JBYJ58RPavapdx0h3jdgE08hr+N3z0OzvQu34yr2kW/h1mfgAs7PLzpWiZaynP4xLoCx8nr51JMZvQcboWOydeM5we25kPkCnb9Y4CTw+KX1R1flvtW/7FgwmTHDoAIVkaXFiI+NVMEz/91311PM+ieg6hNxZoZzwTIyE3pUGAxWgwb8YADfQONss4jNdo5p4p3TVYbfjpF/sjdO2TEXboCUrEE6rae61gderX3jSU2epufVtXIUK3BbkeeW7cGpTxH8vKHCfdk+7RTK62Yb03b1/HHqzz8P1dC+djN2bErO5ZyvQOItWBbaLu3jFb+S6hrMGxCKgB0K4dz/4Jk54dIMkdyQn9R0AUs8x/IkSC7b9HjvqUPvoSET1gtbkWolICQVppZcOoTEmkiYAopxnudMxlRhuSnVSQKvBJAfCv+wTqOQTrGTK2Bn2d+Q/N92MNHUsrwmb3nq+gtSP+GjOe6rB8BEvR/K4ZPJB45w7yCw/0qh7LZlry+A/P/7s1lXQCDKc+vW/bVVrBJSeWH5DiOp/8nOg1iOtisesRmscJBGi9Yx8bNmGbKQDpt8Bnxk2QmSTPf62WEmA=
  on:
    tags: true
    repo: hmcts/os-places-client-node
