language: node_js
node_js:
- node
script:
- yarn build
- yarn lint
- yarn coverage
deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: tfjkK9INro3YSPLfm5gvkxXzQEataLxdovwdq6FS97h8tcfJNUflXJ9XiYYSynEZaQG3n0b5qANaRTXVzdB03BS27pGLskJBDnGfwixa+M21u6P7IiXYAUKr70nPN/Y9JG9Rc0QhdICxLcelnirJ8jplECvzzbw3Q8Ng9g1yxh2/z3ZayoMdSc1ckxFj54LXM4FDLtvX/bJX5zxM5WXgRXVp1PqNNVYf5GiM8c2R0vNQwDgsKMH9CPusTJOXUkl0Fht1D9oco1DxAeApV+MetCP8kNcvC60nTB+HqNzbYn2Mgm7api3jZyGEsAUnAUzochh5LkDrUoJQSXBiBxQWHHCQEncl2yOSdjPkvEgVOjGH2Nnz134FX+nUXDTRG/owsrBL1iQzHMAxBB+Bkm/n/5IBsyusZnz3u4AhQ8W2jheyx2MBkRz9WA9SI9MNjdljXAPRXpXLx6C+weLT2jDbenLcdbSngMmBO+tl1q96XpFskyOiMAdDsg9VUVIJxmKaQuo4Gd84Ru3gebkD9OlxOxN+tjjRZT5nFlZ6ywwvmEK5VHNdSVqNdMr7uZd0iSNbrQXShmWmsZgGkrxIU3JAftv66cB7K8Avj7+Yd7JM8+6tZ/sftFsl4tFRt9Df+n6bwQ+0LazX7Ml4abu1DiEethIR4LROIT6djovTmurR2QU=
  on:
    tags: true
    repo: hmcts/os-places-client-node
