language: node_js
node_js:
- node
script:
- yarn build
- yarn lint
- yarn coverage
deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: gR23utvqQQr8+iW2eSuVoU4UuI5nSTpeuSKlgSzLCLL+/kFzQSPhYyDgLrSoLn3wVeTUusVnwlXfzHran3tYuulWqK1w6WXQMvujKi8LW46Y7cOXk+S5LMTKsuDJJF1HltT8edr8nAJcm2VDvPBM18DvTlggLQnFx1vBAeWozTE6cm/l1TlYK4Qwl0yuLtxzvR/VsZKqMefJoiFPXVyhxoo9qBdQK8leV5JoTpPFi3ncrx6HRwRLMz1F5JNwqdh9AkG1dq2ndVKoTAq6nIaJqKHtyvGYmfVjCuNpcbzwUXO/0b82O/FBb6EfMkbr1xZYuP0h6/vRKdNhJLRPUPwMgBr588LNgAjFNeXX0seIpxhZTTq0a9KVPiHgw2P3U0GvUcE8Zi/B8A36BpIYha/j4jS5EO9z2oohINAHNV0xsXkvl5kS413PtNkLL8A+Rkmmvex9NiGRJvesTFqlsPbAVvznYG5ryAKBqlKJkGT80JbTedjjEiis8poILcOxrRqkqb36y6sTLxyXSFj0jDG3YWDcrYZI5gPkzxUmYFce5/4+0poD5HyzNwEWzzcFFwYcd2jBzZPT+4YX+fg8gqsUZuzLenqCuPedrf2hQGpamg7WosZ0lNhymP9NpEzQidByAlCy6KuntSwiL49TdgzjUop8BpuY7LG5iVxYox6tlRI=
  on:
    tags: true
    repo: hmcts/os-places-client-node
